jarwayy/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from login_app import views
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^login_app/',include('login_app.urls')),
    url(r'^logout/',views.user_logout,name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

login_app/urls.py
from django.conf.urls import url
from . import views

app_name='login_app'

urlpatterns=[
    url(r'^$',views.register,name='register'),
    url(r'^login/',views.user_login,name='login'),
    url(r'^profile/',views.profile_info,name='profile_info'),
    url(r'^question/',views.question_list,name='question_list'),
    url(r'^answer/(?P<questions_id>\d+)',views.answer_list,name='answer_list'),
]

login_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
    user=models.OneToOneField(User, related_name='profile')
    age=models.PositiveSmallIntegerField()
    profile_pic=models.ImageField(blank=True)

    def __str__(self):
        return self.user.username

class Questions(models.Model):
    question_user=models.ForeignKey(UserProfileInfo,related_name='questions',on_delete=models.CASCADE)
    question=models.CharField(max_length=256)
    question_time=models.DateTimeField()

    def __str__(self):
        return str(self.id)

class Answers(models.Model):
    answer_user=models.ForeignKey(UserProfileInfo,related_name='answers',on_delete=models.CASCADE)
    answer_to_question=models.ForeignKey(Questions)
    answer=models.CharField(max_length=256)
    answer_time=models.DateTimeField()

    def __str__(self):
        return str(self.id)

login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('age','profile_pic')

login_app/views.py
from django.shortcuts import render
from .forms import UserForm,UserProfileInfoForm
from .models import UserProfileInfo,Questions,Answers
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
import datetime
# Create your views here.

def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def index(request):
    return render(request,'index.html')

def register(request):
    registered=False
    if request.method == 'POST':
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user
            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']
            profile.save()
            registered=True
            login(request,user)
            return HttpResponseRedirect(reverse('login_app:profile_info'))
        else:
            print(user_form.errors,profile_form.errors)
            return render(request,'register.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()
        return render(request,'register.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request):

    if request.method =="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')
        #print(username,password)
        user=authenticate(username=username,password=password)
        print("Hello")
        #print(str(user))
        if user:
            login(request,user)
            return HttpResponseRedirect(reverse('login_app:profile_info'))
        else:
            print('Username: {} and Password: {}'.format(username,password))
            return HttpResponse("Invalid ID and Password.")
    else:
        return render(request,'login.html',{})

def profile_info(request):
    if request.user.is_authenticated:
        user=request.user
        question=Questions.objects.all().filter(question_user=user.profile)
        answer=Answers.objects.all().filter(answer_user=user.profile)
        return render(request,'profile_page.html',{'user':user,'question':question,'answer':answer})
    else:
        return HttpResponseRedirect(reverse('login_app:login'))


def question_list(request):
    if request.user.is_authenticated:
        if request.method=='POST':
            if request.POST['action']=='Delete':
                identity=request.POST.get('identity')
                Questions.objects.filter(id=identity).delete()
                print("Question Deletion Done")
            else:
                ques=request.POST.get("Quest")
                ques_object=Questions.objects.create(question_user=request.user.profile,
                                                    question=ques,question_time=datetime.datetime.now())
            return HttpResponseRedirect(reverse('login_app:profile_info'))
        else:
            current_user=request.user
            question=Questions.objects.all().reverse()
            return render(request,'ht3.html',{'current_user':current_user,'question':question})
    else:
        return HttpResponseRedirect(reverse('login_app:login'))

def answer_list(request,questions_id):
    print(questions_id)
    if request.user.is_authenticated:
        question=Questions.objects.get(id=questions_id)

        if request.method=='POST':
            if request.POST['action']=='Delete':
                identity=request.POST.get('identity')
                Answers.objects.filter(id=identity).delete()
                print("Answer Deletion Done")
            else:
                answe=request.POST.get("Answer")
                ans_object=Answers.objects.create(answer_user=request.user.profile,
                                                answer_to_question=question,answer=answe,answer_time=datetime.datetime.now())
            return HttpResponseRedirect(reverse('login_app:profile_info'))
        else:
            current_user=request.user
            print(current_user.username)
            print(question.question_user.user.username)
            answer=Answers.objects.all().filter(answer_to_question=question)
            answer=list(answer)
            answer=answer
            return render(request,'ht4.html',{'current_user':current_user,'question':question,'answer':answer})

login_app/templates/answers.html
{%extends 'base.html'%}
{%block body_block%}
<h4>Question:{{question.question}}</h4>

{%if current_user.username != question.question_user.user.username%}
  <form method="post">
    {%csrf_token%}
    <textarea placeholder="Enter your text here" name="Answer" rows="4" cols="80"></textarea>
    <input type="submit" value="Submit">
  </form>
{%endif%}

{%if answer%}
  {%for ans in answer%}
    <h4>Answer:{{ans.answer}}</h4>User:{{ans.answer_user.user.username}}
    Date:{{ans.answer_time|date:"SHORT_DATE_FORMAT"}}
    Time:{{ans.answer_time|time}}
    <br><br>
  {%endfor%}
{%else%}
<h3>No Answers yet posted</h3>
{%endif%}

{%endblock%}

login_app/templates/base.html
<!DOCTYPE html>
{%load staticfiles%}
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-link" href="{%url 'index'%}">HOME</a></li>
          {%if not request.user.is_authenticated%}
            <li><a class="navbar-link" href="{%url 'login_app:register'%}">Register</a></li>
          {%endif%}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {%if user.is_authenticated%}
            <li style="float:center;"><a class="navbar-link" href="{%url 'login_app:question_list'%}">Recent posts</a></li>
            <li style="float:center;"><a class="navbar-link" href="{%url 'login_app:profile_info'%}"><strong>{{user.username}}</strong></a></li>
            <li style="float:right;"><a class="navbar-link" href="{%url 'logout'%}">Logout</a></li>
          {%else%}
            <li style="float:right;"><a class="navbar-link" href="{%url 'login_app:login'%}">Login</a></li>
          {%endif%}

        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {%endblock%}
    </div>

  </body>
</html>

login_app/templates/ht3.html
{%extends 'base.html'%}
{%block body_block%}

    <meta content="text/html; charset=UTF-8" http-equiv="content-type">
    <title>HTML::Template / Discussion / Discussion</title>

        <link rel="stylesheet" type="text/css" href="https://a.fsdn.com/allura/nf/1520885736/_ew_/theme/sftheme/css/forge.css">

</head>
<body>



  <div class="grid-40">
                <h2 class="dark title">Open Discussion</h2>
  <div>



<div class="discussion_subscription_form">
<div id="forum_threads">
  <table class="forum-list clear">
    <thead>
      <tr>

        <th class="topic">Topics/Questions</th>
        <th>Answers</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody class="forum-list">

{%if question%}
{%for q in question%}

      <tr class="even">


        <td class="topic">


      <p> <a href="{%url 'login_app:answer_list' q.id%}"><b>{{q.question}}</b></a></p>
          <span>By

            <a href="#">

                    {{q.question_user.user.username}}

            </a>

    </span> on {{q.question_time|date:"SHORT_DATE_FORMAT"}} {{q.question_time|time}}
        </td>

        <td>{{q.answers_set.count}}</td>
        <td></td>


          <td>

          </td>
          <td>
            {%if q.question_user.user.username == current_user.username%}
            <form action="{%url 'login_app:question_list'%}" method="post">
            {%csrf_token%}
            <input type="hidden" name="identity" value="{{q.id}}">
            <input type="submit" name="action" value="Delete">
            </form>
            {%endif%}
          </td>
      </tr>
{%endfor%}
{%endif%}

    </tbody>
  </table>
  <form method="post">
    {%csrf_token%}
    <textarea placeholder="Enter your Question here" name="Quest" rows="4" cols="80"></textarea>
    <input type="submit" name="action" style="position: absolute;" value="Submit">
  </form>
</div>

</div>
</div>
</div>
</body>
{%endblock%}

login_app/templates/ht4.html
{%extends 'base.html'%}
{%block body_block%}

    <meta content="text/html; charset=UTF-8" http-equiv="content-type">
    <title>HTML::Template / Discussion / Discussion</title>

        <link rel="stylesheet" type="text/css" href="https://a.fsdn.com/allura/nf/1520885736/_ew_/theme/sftheme/css/forge.css">

</head>
<body>



  <div class="grid-40">
                <h2 class="dark title">Open Discussion</h2>
  <div>



<div class="discussion_subscription_form">
<div id="forum_threads">
  <table class="forum-list clear">
    <thead>
      <tr>

        <th class="topic"><h2><b>Question:</b>{{question.question}}</h2></th>
        <th></th>
      </tr>
    </thead>

    <tbody class="forum-list">

{%if answer%}
{%for ans in answer%}

      <tr class="even">


        <td class="topic">


          <p><b>Answer:</b>{{ans.answer}}</p>
          <span>By

            <a href="#">

                    User:{{ans.answer_user.user.username}}

            </a>

    </span> Date:{{ans.answer_time|date:"SHORT_DATE_FORMAT"}} Time:{{ans.answer_time|time}}
        </td>
        <td>
          {%if ans.answer_user.user.username == current_user.username%}
          <form action="{%url 'login_app:answer_list' question.id%}" id="{{ans.id}}" method="post">
          {%csrf_token%}
          <input type="hidden" name="identity" value="{{ans.id}}">
          <input type="submit" name="action" value="Delete">
          </form>
          {%endif%}
        </td>
      </tr>
      <tr>


    </tr>

{%endfor%}

{%else%}
<tr>
<td>
<h2><big>No Answers yet posted</big></h2></td></tr>

{%endif%}

    </tbody>
  </table>
  {%if current_user.username != question.question_user.user.username%}
    <form method="post">
      {%csrf_token%}
      <textarea placeholder="Enter your Answer here" name="Answer" rows="4" cols="80"></textarea>
      <input type="submit" name="action" style="position: absolute;" value="Submit">
    </form>
  {%endif%}

</div>

</div>
</div>
</div>
</body>
{%endblock%}

login_app/templates/index.html
{% extends 'base.html' %}
{%block body_block%}

<div class="jumbotron">
  <h3>Welcome to Discussion-Forum App!</h3>
  <hr>
  <h4>To either view or to write a question or an answer kindly Register.</h4>
  <h4>Please Login if you already have an account.</h4>
</div>
{%endblock%}

login_app/templates/login.html
{%extends 'base.html'%}
{%block body_block%}
<div class="jumbotron">

  <form method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">

  </form>
  <hr>
  <a href="{%url 'login_app:register'%}">Haven't registered yet? Click Here!</a>
</div>

{%endblock%}

login_app/templates/profile_page.html
{%extends 'base.html'%}
{%block body_block%}
<div class="jumbotron">
<h3><center>Profile Page</center></h3>
  {%csrf_token%}
  {%if user%}
    <strong><big>Username:</big></strong>{{user.username}}</br>
    <strong><big>Email ID:</big></strong>{{user.email}}</br>
    <strong><big>Age:</big></strong>{{user.profile.age}}</br>
    {%if user.profile.profile_pic%}
      <strong><big>Profile Photo:</big></strong><img src="{{user.profile.profile_pic.url}}" alt="">
    {%endif%}

    <h3>My Questions:</h3>
    {%if question%}
    {%for q in question%}
    <a href="{%url 'login_app:answer_list' q.id%}"><h3>{{q.question}}</h3></a>
    <br>
    {%endfor%}
    {%endif%}

    <h3>My Answers:</h3>
    {%if answer%}
      {%for ans in answer%}
        <p><b>Question:</b>{{ans.answer_to_question.question}}</p>
        <p><b>Answer:</b>{{ans.answer}}</p>
        <br>
      {%endfor%}
    {%else%}
    <h4 style="color:red">'''No Answers yet posted'''</h4>
    {%endif%}
  {%endif%}
</div>




{%endblock%}

login_app/templates/questions.html
{%extends 'base.html'%}
{%block body_block%}
<form method="post">
  {%csrf_token%}
  <textarea placeholder="Enter your text here" name="Quest" rows="4" cols="80"></textarea>
  <input type="submit" value="Submit">
</form>
{%if question%}
{%for q in question%}
<a href="{%url 'login_app:answer_list' q.id%}">{{q.question}}</a>User:{{q.question_user.user.username}}
Date:{{q.question_time|date:"SHORT_DATE_FORMAT"}}
Time:{{q.question_time|time}}
<br>
{%endfor%}
{%endif%}

{%endblock%}

login_app/templates/register.html
{%extends 'base.html'%}
{%block body_block%}
<div class="jumbotron">

  <form method="post" enctype="multipart/form-data">
    {%csrf_token%}
    {{user_form.as_p}}
    {{profile_form.as_p}}
    <input type="submit" name="" value="Register">
  </form>
  <hr>
  <a href="{%url 'login_app:login'%}">Already have an account? Click Here!</a>
</div>

{%endblock%}